/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JDesktopPane;
import main.main;
//import javax.swing.JDesktopPane;


/**
 *
 * @author salomeamayarios
 */
public class frameMenu1 extends javax.swing.JFrame {
    
    public static JDesktopPane jDesktopPane_menu;

    /**
     * Creates new form frameMenu1
     */
    public frameMenu1() {
        this.setResizable(false);
        
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("SISTEMA DE VENTAS - SUPER MARKET");
        
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110)); // 110 pixeles ancho de la parte de abajo
        this.add(jDesktopPane_menu);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_usuario = new javax.swing.JMenu();
        jMenuItem_Nuevo_Usuario = new javax.swing.JMenuItem();
        jMenuItem_Gestionar_Usuario = new javax.swing.JMenuItem();
        jMenu_producto = new javax.swing.JMenu();
        jMenuItem_Nuevo_producto = new javax.swing.JMenuItem();
        jMenuItem_gestionar_producto = new javax.swing.JMenuItem();
        jMenuItem_actualizar_stock = new javax.swing.JMenuItem();
        jMenu_cliente = new javax.swing.JMenu();
        jMenuItem_nuevo_cliente = new javax.swing.JMenuItem();
        jMenuItem_gestionar_cliente = new javax.swing.JMenuItem();
        jMenu_categoria = new javax.swing.JMenu();
        jMenuItem_nueva_categoria = new javax.swing.JMenuItem();
        jMenuItem_gestionar_categoria = new javax.swing.JMenuItem();
        jMenu_facturar = new javax.swing.JMenu();
        jMenuItem_nueva_venta = new javax.swing.JMenuItem();
        jMenuItem_gestionar_venta = new javax.swing.JMenuItem();
        jMenu_reportes = new javax.swing.JMenu();
        jMenuItem_reporte_cliente = new javax.swing.JMenuItem();
        jMenuItem_reporte_categoria = new javax.swing.JMenuItem();
        jMenuItem_reporte_producto = new javax.swing.JMenuItem();
        jMenuItem_reporte_venta = new javax.swing.JMenuItem();
        jMenu_historial = new javax.swing.JMenu();
        jMenuItem_ver_historial = new javax.swing.JMenuItem();
        jMenu_cerrar_sesion = new javax.swing.JMenu();
        jMenuItem_cerrar_sesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu_usuario.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/usuario.png")); // NOI18N
        jMenu_usuario.setText("Usuario");
        jMenu_usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_usuario.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_Nuevo_Usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_Nuevo_Usuario.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/nuevo-cliente.png")); // NOI18N
        jMenuItem_Nuevo_Usuario.setText("Nuevo Usuario");
        jMenuItem_Nuevo_Usuario.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_Nuevo_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Nuevo_UsuarioActionPerformed(evt);
            }
        });
        jMenu_usuario.add(jMenuItem_Nuevo_Usuario);

        jMenuItem_Gestionar_Usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_Gestionar_Usuario.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/configuraciones.png")); // NOI18N
        jMenuItem_Gestionar_Usuario.setText("Gestionar Usuarios");
        jMenuItem_Gestionar_Usuario.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_usuario.add(jMenuItem_Gestionar_Usuario);

        jMenuBar1.add(jMenu_usuario);

        jMenu_producto.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/producto.png")); // NOI18N
        jMenu_producto.setText("Producto");
        jMenu_producto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_producto.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_Nuevo_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_Nuevo_producto.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/nuevo-producto.png")); // NOI18N
        jMenuItem_Nuevo_producto.setText("Nuevo Producto");
        jMenuItem_Nuevo_producto.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_Nuevo_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Nuevo_productoActionPerformed(evt);
            }
        });
        jMenu_producto.add(jMenuItem_Nuevo_producto);

        jMenuItem_gestionar_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_gestionar_producto.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/producto.png")); // NOI18N
        jMenuItem_gestionar_producto.setText("Gestionar Productos");
        jMenuItem_gestionar_producto.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_producto.add(jMenuItem_gestionar_producto);

        jMenuItem_actualizar_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_actualizar_stock.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/nuevo.png")); // NOI18N
        jMenuItem_actualizar_stock.setText("Actualizar Stock");
        jMenuItem_actualizar_stock.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_producto.add(jMenuItem_actualizar_stock);

        jMenuBar1.add(jMenu_producto);

        jMenu_cliente.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/cliente.png")); // NOI18N
        jMenu_cliente.setText("Cliente");
        jMenu_cliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_cliente.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nuevo_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_nuevo_cliente.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/nuevo-cliente.png")); // NOI18N
        jMenuItem_nuevo_cliente.setText("Nuevo Cliente");
        jMenuItem_nuevo_cliente.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_cliente.add(jMenuItem_nuevo_cliente);

        jMenuItem_gestionar_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_gestionar_cliente.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/cliente.png")); // NOI18N
        jMenuItem_gestionar_cliente.setText("Gestionar Clientes");
        jMenuItem_gestionar_cliente.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_cliente.add(jMenuItem_gestionar_cliente);

        jMenuBar1.add(jMenu_cliente);

        jMenu_categoria.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/categorias.png")); // NOI18N
        jMenu_categoria.setText("Categoria");
        jMenu_categoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_categoria.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nueva_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_nueva_categoria.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/nuevo.png")); // NOI18N
        jMenuItem_nueva_categoria.setText("Nueva Categoria");
        jMenuItem_nueva_categoria.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_nueva_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nueva_categoriaActionPerformed(evt);
            }
        });
        jMenu_categoria.add(jMenuItem_nueva_categoria);

        jMenuItem_gestionar_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_gestionar_categoria.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/categorias.png")); // NOI18N
        jMenuItem_gestionar_categoria.setText("Gestionar Categorias");
        jMenuItem_gestionar_categoria.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_gestionar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_categoriaActionPerformed(evt);
            }
        });
        jMenu_categoria.add(jMenuItem_gestionar_categoria);

        jMenuBar1.add(jMenu_categoria);

        jMenu_facturar.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/carrito.png")); // NOI18N
        jMenu_facturar.setText("Facturar");
        jMenu_facturar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_facturar.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nueva_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_nueva_venta.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/anadir.png")); // NOI18N
        jMenuItem_nueva_venta.setText("Nueva Venta");
        jMenuItem_nueva_venta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_facturar.add(jMenuItem_nueva_venta);

        jMenuItem_gestionar_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_gestionar_venta.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/configuraciones.png")); // NOI18N
        jMenuItem_gestionar_venta.setText("Gestionar Ventas");
        jMenuItem_gestionar_venta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_facturar.add(jMenuItem_gestionar_venta);

        jMenuBar1.add(jMenu_facturar);

        jMenu_reportes.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/reportes.png")); // NOI18N
        jMenu_reportes.setText("Reportes");
        jMenu_reportes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_reportes.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_reporte_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_reporte_cliente.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/reporte1.png")); // NOI18N
        jMenuItem_reporte_cliente.setText("Reportes Clientes");
        jMenuItem_reporte_cliente.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_reportes.add(jMenuItem_reporte_cliente);

        jMenuItem_reporte_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_reporte_categoria.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/reporte1.png")); // NOI18N
        jMenuItem_reporte_categoria.setText("Reportes Categorias");
        jMenuItem_reporte_categoria.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_reportes.add(jMenuItem_reporte_categoria);

        jMenuItem_reporte_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_reporte_producto.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/reporte1.png")); // NOI18N
        jMenuItem_reporte_producto.setText("Reportes Productos");
        jMenuItem_reporte_producto.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_reportes.add(jMenuItem_reporte_producto);

        jMenuItem_reporte_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_reporte_venta.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/reporte1.png")); // NOI18N
        jMenuItem_reporte_venta.setText("Reportes Ventas");
        jMenuItem_reporte_venta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_reportes.add(jMenuItem_reporte_venta);

        jMenuBar1.add(jMenu_reportes);

        jMenu_historial.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/historial1.png")); // NOI18N
        jMenu_historial.setText("Historial");
        jMenu_historial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_historial.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_ver_historial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_ver_historial.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/historial1.png")); // NOI18N
        jMenuItem_ver_historial.setText("Ver Historial");
        jMenuItem_ver_historial.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_historial.add(jMenuItem_ver_historial);

        jMenuBar1.add(jMenu_historial);

        jMenu_cerrar_sesion.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/cerrar-sesion.png")); // NOI18N
        jMenu_cerrar_sesion.setText("Cerrar Sesion");
        jMenu_cerrar_sesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_cerrar_sesion.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem_cerrar_sesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_cerrar_sesion.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/cerrar-sesion.png")); // NOI18N
        jMenuItem_cerrar_sesion.setText("Cerrar Sesion");
        jMenuItem_cerrar_sesion.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_cerrar_sesion.add(jMenuItem_cerrar_sesion);

        jMenuBar1.add(jMenu_cerrar_sesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_Nuevo_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Nuevo_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Nuevo_UsuarioActionPerformed

    private void jMenuItem_Nuevo_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Nuevo_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Nuevo_productoActionPerformed

    private void jMenuItem_nueva_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nueva_categoriaActionPerformed
        interCategoria inCategoria = new interCategoria();
        jDesktopPane_menu.add(inCategoria);
        inCategoria.setVisible(true);

    }//GEN-LAST:event_jMenuItem_nueva_categoriaActionPerformed

    private void jMenuItem_gestionar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_categoriaActionPerformed
    
     InterGestionarCategoria interGestionarCategoria = new InterGestionarCategoria();
     jDesktopPane_menu.add(interGestionarCategoria);
     interGestionarCategoria.setVisible(true);
        

    }//GEN-LAST:event_jMenuItem_gestionar_categoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                main lo = new main();
                lo.iniciar();
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Gestionar_Usuario;
    private javax.swing.JMenuItem jMenuItem_Nuevo_Usuario;
    private javax.swing.JMenuItem jMenuItem_Nuevo_producto;
    private javax.swing.JMenuItem jMenuItem_actualizar_stock;
    private javax.swing.JMenuItem jMenuItem_cerrar_sesion;
    private javax.swing.JMenuItem jMenuItem_gestionar_categoria;
    private javax.swing.JMenuItem jMenuItem_gestionar_cliente;
    private javax.swing.JMenuItem jMenuItem_gestionar_producto;
    private javax.swing.JMenuItem jMenuItem_gestionar_venta;
    private javax.swing.JMenuItem jMenuItem_nueva_categoria;
    private javax.swing.JMenuItem jMenuItem_nueva_venta;
    private javax.swing.JMenuItem jMenuItem_nuevo_cliente;
    private javax.swing.JMenuItem jMenuItem_reporte_categoria;
    private javax.swing.JMenuItem jMenuItem_reporte_cliente;
    private javax.swing.JMenuItem jMenuItem_reporte_producto;
    private javax.swing.JMenuItem jMenuItem_reporte_venta;
    private javax.swing.JMenuItem jMenuItem_ver_historial;
    private javax.swing.JMenu jMenu_categoria;
    private javax.swing.JMenu jMenu_cerrar_sesion;
    private javax.swing.JMenu jMenu_cliente;
    private javax.swing.JMenu jMenu_facturar;
    private javax.swing.JMenu jMenu_historial;
    private javax.swing.JMenu jMenu_producto;
    private javax.swing.JMenu jMenu_reportes;
    private javax.swing.JMenu jMenu_usuario;
    // End of variables declaration//GEN-END:variables
}
