package vista;

import controlador.controlador_categoria;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Categoriaa;

/**
 *
 * @author salomeamayarios
 */
public class interCategoria extends javax.swing.JInternalFrame {

    public interCategoria() {
        initComponents();
        this.setSize(new Dimension(400, 200));
        this.setTitle("Nueva Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_descripcion = new javax.swing.JTextField();
        jButton1_guardar_categor = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva Categoria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion categoria: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTextField_descripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, -1));

        jButton1_guardar_categor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1_guardar_categor.setText("Guardar");
        jButton1_guardar_categor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_guardar_categorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_guardar_categor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, 30));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon("/Users/salomeamayarios/NetBeansProjects/SistemaSupermercado/fondo3.jpg")); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_descripcionActionPerformed

    private void jButton1_guardar_categorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_guardar_categorActionPerformed

        Categoriaa categoria = new Categoriaa();
        controlador_categoria controlCategoria = new controlador_categoria();

        // validar los campos vacios 
        if (jTextField_descripcion.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Complete todos los campos");

        } else {

            if (!controlCategoria.existeCategoria(jTextField_descripcion.getText().trim())) {
                categoria.setDescripcion(jTextField_descripcion.getText().trim());
                categoria.setEstado(1);

                if (controlCategoria.guardar(categoria)) {
                    JOptionPane.showMessageDialog(null, "Registro exitoso");

                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar");

                }

            } else {
                JOptionPane.showMessageDialog(null, "La categoria ingresada ya esta registrada en la Base de datos");

            }

        }
        //limpiar campo
        jTextField_descripcion.setText("");

    }//GEN-LAST:event_jButton1_guardar_categorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_guardar_categor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField jTextField_descripcion;
    // End of variables declaration//GEN-END:variables
}
